apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubernetes-tutorial-service1-deployment
  labels:
    app: kubernetes-tutorial-service1
spec:
  selector:
    matchLabels:
      app: kubernetes-tutorial-service1 
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-service1
    spec:
      containers:
      - name: service1
        image: kubernetestutorialcode_service1:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

