apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubernetes-tutorial-service2-deployment
  labels:
    app: kubernetes-tutorial-service2
spec:
  selector:
    matchLabels:
      app: kubernetes-tutorial-service2 
  template:
    metadata:
      labels:
        app: kubernetes-tutorial-service2
    spec:
      containers:
      - name: service1
        image: kubernetestutorialcode_service2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80

